= csoftz-learn-software-testing

v1.0.0-Sep.18/2017

Contains all C#, Java, etc., projects used to study TDD, BDD and in general software testing.

Each folder contains a study problem, read the docs to know what is it all about.

== palindrome
This is an example of using Palindromes, but with a twist.

* **docs:** contains some guidance about the problem to tacke.
* **language:** Contains projects and solutions written in the named folder languages. That is,
'palindrome-framework' holds the '.NET Framework 4.6.1' projects, whereas 'palindrome-core'
holds '.NET Core 1.1' projects.

=== VS Studio 2017 Setup
==== .NET Framework Solution
For classic .NET Framework
1. Add new project  to solution 
2. Select Installed > Visual C# > Windows Classic Desktop > Class Library (.NET Framework)
3. Next is to create the Test project
4. Add new project to solution
5. Select Insalled > Visual C# > Test > Unit Test Project (.NET Framework)

[NOTE]
====
The test framework used here is 'Microsoft.Test.SDK'.
====

==== .NET Core Solution
For .NET Core
1. Add new project to solution
2. Select Insalled > Visual C# > .NET Core > Class Library (.NET Core)
3. Next is to create the Test project.
4. Add new project to solution
5. Select Insalled > Visual C# > Test > xUnit Test Project (.NET Core)

[NOTE]
====
The test framework used here is 'xUnit'.
====
